name: GitHub Traffic Analytics

on:
  schedule:
    - cron: '0 0 * * *' # Tự động chạy vào 0h mỗi ngày
  workflow_dispatch: # Nút bấm chạy bằng tay luôn

jobs:
  traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get Traffic Data
        uses: sangonzal/repository-traffic-action@v0.1.6
        env:
          FEED_TOKEN: ${{ secrets.METRICS_TOKEN }}
          TRAFFIC_ACTION_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          # Bot sẽ tự động tạo riêng một nhánh tên là 'traffic' để cất số liệu
          TRAFFIC_BRANCH: 'traffic'
