name: GitHub Traffic Analytics

on:
  schedule:
    - cron: '0 0 * * *' # Hệ thống tự chạy vào 0h mỗi ngày
  workflow_dispatch: # Tạo nút bấm để tự kích hoạt chạy thử ngay lập tức

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Traffic Metrics Graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          repo: MANGA-TRANSLATION-AUTOMATION
          user: QuanHoang05
          base: ""
          plugin_traffic: yes
          plugins_errors_fatal: yes
          filename: traffic.svg # Tên file ảnh biểu đồ xuất ra
